# Generated by Django 3.1.4 on 2021-02-24 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 24, 14, 43, 37, 992528), verbose_name='Fecha de publicacion'),
        ),
    ]
